language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - pip check
  - pytest ./src/tests -s
env:
  RABBITMQ_DEFAULT_USER="user"
  RABBITMQ_DEFAULT_PASS="password"
  RABBITMQ_DEFAULT_HOST="rabbitmq"
  MEMCACHED_HOST="memcached"
  POSTGRES_USER="currency"
  POSTGRES_DB="currency"
  POSTGRES_PASSWORD="jsdo47d2YRTw24Asdf"
  POSTGRES_HOST="postgres"
  SECRET_KEY="fp_grwa77&d75%01dziwslea2*t*(fmas6rrbyg+nbr%k$$wr8"
  SERVER="production"
  ALLOWED_HOSTS="127.0.0.1,localhost,*"
  EMAIL_HOST="smtp.gmail.com"
  EMAIL_USE_TLS="True"
  EMAIL_PORT="587"
  EMAIL_HOST_USER="testdjangohillel@gmail.com"
  EMAIL_HOST_PASSWORD="hilleldjango2020"
  EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL="EMAIL_HOST_USER"
  FLOWER_PORT="5555"