version: "3.3"

services:
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
    - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq
    env_file: .env
    restart: always
    ports:
      - "5672:5672"

  backend:
    env_file: .env
    build: .
    container_name: backend
    # command: tail -f /dev/null
    command: python ./src/manage.py runserver 0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
    - ./:/srv/project

#  worker:
#    build: .
#    restart: always
#    container_name: worker
#    env_file: .env
#    command: bash -c cd src/ && celery worker settings --concurrency=1 --loglevel=INFO
#    depends_on:
#      - rabbitmq