SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_VKURSE = 3
SOURCE_O_O_KHARKIV = 4
SOURCE_CREDIT_DNIPRO = 5
SOURCE_ALFA_BANK = 6
SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_VKURSE, 'Vkurse'),
    (SOURCE_O_O_KHARKIV, 'O_O_KHARKIV'),
    (SOURCE_CREDIT_DNIPRO, 'Bank Credit Dnipro'),
    (SOURCE_ALFA_BANK, 'Alfa Bank'),
)

CURRENCY_TYPE_USD = 1
CURRENCY_TYPE_EUR = 2
CURRENCY_TYPE_CHOICES = (
    (CURRENCY_TYPE_USD, 'USD'),
    (CURRENCY_TYPE_EUR, 'EUR'),
)

RATE_TYPE_SALE = 1
RATE_TYPE_BUY = 2
RATE_TYPE_CHOICES = (
    (RATE_TYPE_SALE, 'Sale'),
    (RATE_TYPE_BUY, 'Buy')
)
