# Generated by Django 2.2.12 on 2020-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'O_O_KHARKIV'), (5, 'Bank Credit Dnipro'), (6, 'Alfa Bank')]),
        ),
    ]
